[workspace]
members = [
    "crates/feeder_core",
    "crates/app_gui",
    "crates/effnet_train"
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1", features = ["derive"] }
